// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.5
//   protoc               v3.20.3
// source: proto/auth.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "auth";

export interface returnUserData {
  response: string;
}

export interface userData {
  name: string;
  email: string;
  password: string;
}

export const AUTH_PACKAGE_NAME = "auth";

export interface authServiceClient {
  registerUser(request: userData): Observable<returnUserData>;
}

export interface authServiceController {
  registerUser(request: userData): Promise<returnUserData> | Observable<returnUserData> | returnUserData;
}

export function authServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["registerUser"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("authService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("authService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const AUTH_SERVICE_NAME = "authService";
