// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.5
//   protoc               v6.31.1
// source: proto/user.prot
// no idea 

//s

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "user";

export interface GetProfileRequest {
  user_id: string;
  userId: string;
}

export interface GetProfileResponse {
  id: string;
  email: string;
  firstName: string;
  lastName: string;
}

export const USER_PACKAGE_NAME = "user";

export interface UserServiceClient {
  getProfile(request: GetProfileRequest): Observable<GetProfileResponse>;
}

export interface UserServiceController {
  getProfile(
    request: GetProfileRequest,
  ): Promise<GetProfileResponse> | Observable<GetProfileResponse> | GetProfileResponse;
}

export function UserServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["getProfile"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("UserService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("UserService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const USER_SERVICE_NAME = "UserService";
